### PR TITLE
jq is not available if one becomes root

### PR DESCRIPTION
**Pull request by andy-a-d-nguyen**
It is available if one is not root.

### CODE REVIEW

**Comment by ameowlia** [comment]
🤔 I will investigate, based on my experience I don't think this is true...

**Comment by zucchinidev** [comment]
Hi @andy-a-d-nguyen, @ameowlia 

I guess it depends on how we become root. We need to propagate the environment variables. It might be good to mention the command `sudo -i`

```bash
router/67d69064-f50f-4b1e-b271-12d828af98ac:~$ sudo -i
router/67d69064-f50f-4b1e-b271-12d828af98ac:~# jq
jq - commandline JSON processor [version 1.7.1]

Usage:	jq [options] <jq filter> [file...]
	jq [options] --args <jq filter> [strings...]
	jq [options] --jsonargs <jq filter> [JSON_TEXTS...]

jq is a tool for processing JSON inputs, applying the given filter to
its JSON text inputs and producing the filter's results as JSON on
standard output.

The simplest filter is ., which copies jq's input to its output
unmodified except for formatting. For more advanced filters see
the jq(1) manpage ("man jq") and/or https://jqlang.github.io/jq/.

Example:

	$ echo '{"foo": 0}' | jq .
	{
	  "foo": 0
	}

For listing the command options, use jq --help.
router/67d69064-f50f-4b1e-b271-12d828af98ac:~# echo $PATH
/var/vcap/bosh/bin:/var/vcap/packages/gorouter/bin:/var/vcap/jobs/bpm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/var/vcap/bosh/bin
router/67d69064-f50f-4b1e-b271-12d828af98ac:~# whereis jq
jq: /var/vcap/data/packages/gorouter/96ecde44eab586cdcb49d5f58cf9f5f479362810/bin/jq
router/67d69064-f50f-4b1e-b271-12d828af98ac:~# exit
logout
router/67d69064-f50f-4b1e-b271-12d828af98ac:~$ sudo su
router/67d69064-f50f-4b1e-b271-12d828af98ac:/var/vcap/bosh_ssh/bosh_7ac931bd61e24ea# echo $PATH
/var/vcap/bosh/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/var/vcap/bosh/bin
router/67d69064-f50f-4b1e-b271-12d828af98ac:/var/vcap/bosh_ssh/bosh_7ac931bd61e24ea# 

```

**Comment by andy-a-d-nguyen** [comment]
That makes sense. I was using `sudo su` and jq wasn't available for that. I'll close this PR.

**Comment by ameowlia** [comment]
Thanks @zucchinidev ! I should probably update any of my instructions to become root to include that...

**Pull request closed without merging**
